services:
  api:
    build: .
    ports:
      - 8000:8000
    command: bash ./entrypoint.sh
    environment:
      - DEBUG=True
      - DB_USER=oren
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DJANGO_SETTINGS=blog.settings
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    restart: always

  db:
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: oren
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432

volumes:
  postgres-data:


