# Generated by Django 5.0.1 on 2024-02-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='did_category_name_appear_in_post',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='num_words',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
