name: Django blog app CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv requirements > requirements.txt
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    # - name: Build and push Docker images
    #   uses: docker/build-push-action@v5.1.0
  
